inventory_shop_system/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("hardware/", include("hardware.urls")),
    path("licenses/", include("licenses.urls")),
    path("", include("users.urls")),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

licenses/urls.py
# filepath: c:\Users\Piotr\Desktop\Inventory-Shop-System\licenses\urls.py
from django.urls import path
from . import views

app_name = "licenses"

urlpatterns = [
    # URLs for Software model
    path("software/", views.software_list_view, name="software_list"),
    path("software/add/", views.software_add_view, name="software_add"),
    path("software/<int:pk>/edit/", views.software_edit_view, name="software_edit"),
    path(
        "software/<int:pk>/delete/", views.software_delete_view, name="software_delete"
    ),
    # URLs for License model
    path("license/", views.license_list_view, name="license_list"),
    path("license/add/", views.license_add_view, name="license_add"),
    path("license/<int:pk>/edit/", views.license_edit_view, name="license_edit"),
    path("license/<int:pk>/delete/", views.license_delete_view, name="license_delete"),
]

users/urls.py
from django.urls import path
from . import views
from django.views.generic.base import RedirectView

app_name = "users"

urlpatterns = [
    # users paths
    path("users/", views.users_list_view, name="users_list"),
    path("users/add/", views.users_add_view, name="users_add"),
    path("users/<int:pk>/edit/", views.users_edit_view, name="users_edit"),
    path("users/<int:pk>/delete/", views.users_delete_view, name="users_delete"),
    # roles paths
    path("roles/", views.roles_list_view, name="roles_list"),
    # redirect from / to users/
    path("", RedirectView.as_view(url="users/", permanent=False)),
    # about view
    path("about/", views.about_view, name="about"),
    # auth paths
    path("signin/", views.signin_view, name="signin"),
    path("signout/", views.signout_view, name="signout"),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.


class Role(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        return self.name


class User(AbstractUser):
    position = models.CharField(max_length=255)
    role = models.ForeignKey(Role, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} ({self.username})"

users/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import User, Role
from django import forms
from django.contrib.auth.hashers import make_password
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.decorators import login_required
from utils.decorators import role_required

# about views


def about_view(request):
    active_nav = "about"
    active_page_title = "About"
    return render(
        request,
        "about.html",
        {
            "active_nav": active_nav,
            "active_page_title": active_page_title,
        },
    )


class UserBaseForm(forms.ModelForm):
    class Meta:
        model = User
        fields = [
            "first_name",
            "last_name",
            "position",
            "role",
            "email",
            "username",
        ]
        widgets = {
            "first_name": forms.TextInput(
                attrs={"placeholder": "First Name"},
            ),
            "last_name": forms.TextInput(
                attrs={"placeholder": "Last Name"},
            ),
            "position": forms.TextInput(
                attrs={"placeholder": "Position"},
            ),
            "email": forms.EmailInput(
                attrs={"placeholder": "E-mail"},
            ),
            "username": forms.TextInput(
                attrs={"placeholder": "Username"},
            ),
        }

    def save(self, commit=True):
        user = super().save(commit=False)
        password = self.cleaned_data.get("password")
        if password:
            user.password = make_password(password)
        if commit:
            user.save()
        return user


class UserAddForm(UserBaseForm):
    password = forms.CharField(
        widget=forms.PasswordInput(attrs={"placeholder": "Password"}), required=True
    )

    class Meta(UserBaseForm.Meta):
        fields = UserBaseForm.Meta.fields


class UserEditForm(UserBaseForm):
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={"placeholder": "Leave blank to keep the current password."}
        ),
        required=False,
    )

    class Meta(UserBaseForm.Meta):
        fields = UserBaseForm.Meta.fields


class RoleForm(forms.ModelForm):
    class Meta:
        model = Role
        fields = [
            "name",
            "description",
        ]
        widgets = {
            "name": forms.TextInput(attrs={"placeholder": "Name"}),
            "description": forms.TextInput(attrs={"placeholder": "Description"}),
        }


class SigninForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ["username", "password"]

        widgets = {
            "username": forms.TextInput(attrs={"placeholder": "Username"}),
            "password": forms.PasswordInput(attrs={"placeholder": "Password"}),
        }


# users views
@login_required
@role_required("Admin", redirect_to="hardware:hardware_list")
def users_list_view(request):
    users = User.objects.all()
    active_nav = "users"
    active_page_title = "User"

    return render(
        request,
        "users/users/users_list.html",
        {
            "users": users,
            "active_nav": active_nav,
            "active_page_title": active_page_title,
        },
    )


@login_required
@role_required("Admin", redirect_to="hardware:hardware_list")
def users_add_view(request):
    active_nav = "users"
    active_page_title = "User"

    if request.method == "POST":
        form = UserAddForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("users:users_list")
    else:
        form = UserAddForm()

    return render(
        request,
        "users/users/users_add.html",
        {
            "form": form,
            "active_nav": active_nav,
            "active_page_title": active_page_title,
        },
    )


@login_required
@role_required("Admin", redirect_to="hardware:hardware_list")
def users_edit_view(request, pk):
    user = get_object_or_404(User, pk=pk)
    active_nav = "users"
    active_page_title = f"Edit User: {user.username}"

    if request.method == "POST":
        form = UserEditForm(request.POST, instance=user)
        if form.is_valid():
            form.save()
            return redirect("users:users_list")

    else:
        form = UserEditForm(instance=user)

    return render(
        request,
        "users/users/users_edit.html",
        {
            "form": form,
            "user": user,
            "active_nav": active_nav,
            "active_page_title": active_page_title,
        },
    )


@login_required
@role_required("Admin", redirect_to="hardware:hardware_list")
def users_delete_view(request, pk):
    user = get_object_or_404(User, pk=pk)
    active_nav = "users"
    active_page_title = f"Delete User: {user.username}"

    if request.method == "POST":
        user.delete()
        return redirect("users:users_list")

    return render(
        request,
        "users/users/users_delete.html",
        {
            "user": user,
            "active_nav": active_nav,
            "active_page_title": active_page_title,
        },
    )


# roles views
@login_required
@role_required("Admin", redirect_to="hardware:hardware_list")
def roles_list_view(request):
    roles = Role.objects.all()
    active_nav = "users"

    return render(
        request,
        "users/roles/roles_list.html",
        {
            "roles": roles,
            "active_nav": active_nav,
        },
    )


# auth views
def signin_view(request):
    active_nav = "sign_in"

    if request.method == "POST":
        username = request.POST["username"]
        password = request.POST["password"]
        user = authenticate(request, username=username, password=password)
        if user:
            login(request, user)
            return redirect("users:users_list")
        else:
            return redirect("users:signin")
    else:
        form = SigninForm()

    return render(
        request,
        "auth/signin.html",
        {
            "form": form,
            "active_nav": active_nav,
        },
    )


def signout_view(request):
    logout(request)
    return redirect("users:signin")

users/templates/users/users_add.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Add User
{% endblock title %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static '/css/users/users-add.css' %}" />
{% endblock extra_css %}
{% block page_title %}
    Add User
{% endblock page_title %}
{% block content %}
    <panel>
    <div class="inner-panel">
        <h3>Users Tables:</h3>
        <ul>
            <li>
                <a href="{% url 'users:users_list' %}" class="selected">Users</a>
            </li>
            <li>
                <a href="{% url 'users:roles_list' %}">Roles</a>
            </li>
        </ul>
    </div>
    </panel>
    <container>
    <content-nav>
        <a href="{% url 'users:users_list' %}" class="action-tab">View Users</a>
        <a href="{% url 'users:users_add' %}" class="action-tab selected">Add User</a>
    </content-nav>
    <content>
        <div class="user-form-container">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">First Name:</label>
                    {{ form.name }}
                    {% if form.name.errors %}<div class="form-error">{{ form.name.errors }}</div>{% endif %}
                </div>
                <div class="form-group">
                    <label for="id_surname">Last Name:</label>
                    {{ form.surname }}
                    {% if form.surname.errors %}<div class="form-error">{{ form.surname.errors }}</div>{% endif %}
                </div>
                <div class="form-group">
                    <label for="id_position">Position:</label>
                    {{ form.position }}
                    {% if form.position.errors %}<div class="form-error">{{ form.position.errors }}</div>{% endif %}
                </div>
                <div class="form-group">
                    <label for="id_id_role">Role:</label>
                    {{ form.id_role }}
                    {% if form.id_role.errors %}<div class="form-error">{{ form.id_role.errors }}</div>{% endif %}
                </div>
                <div class="form-group">
                    <label for="id_email">E-mail:</label>
                    {{ form.email }}
                    {% if form.email.errors %}<div class="form-error">{{ form.email.errors }}</div>{% endif %}
                </div>
                <div class="form-group">
                    <label for="id_username">Username:</label>
                    {{ form.username }}
                    {% if form.username.errors %}<div class="form-error">{{ form.username.errors }}</div>{% endif %}
                </div>
                <div class="form-group">
                    <label for="id_password">Password:</label>
                    {{ form.password }}
                    {% if form.password.errors %}<div class="form-error">{{ form.password.errors }}</div>{% endif %}
                </div>
                <button type="submit">Add User</button>
            </form>
        </div>
    </content>
    </container>
{% endblock content %}

users/templates/users/users_delete.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Delete User
{% endblock title %}
{% block extra_css %}
    <link rel="stylesheet"
          href="{% static 'licenses/css/license/license-delete.css' %}" />
{% endblock extra_css %}
{% block page_title %}
    Delete User
{% endblock page_title %}
{% block content %}
    <panel>
    <div class="inner-panel">
        <h3>License Tables:</h3>
        <ul>
            <li>
                <a href="{% url 'users:users_list' %}" class="selected">Users</a>
            </li>
            <li>
                <a href="{% url 'users:roles_list' %}">Roles</a>
            </li>
        </ul>
    </div>
    </panel>
    <container>
    <content-nav>
        <a href="{% url 'licenses:license_list' %}" class="action-tab">View Users</a>
        <a href="{% url 'licenses:license_add' %}" class="action-tab">Add User</a>
        <a class="action-tab selected">Delete User</a>
    </content-nav>
    <content>
        <div class="user-form-container">
            <form method="post">
                {% csrf_token %}
                <h2>Are you sure you want to delete this user?</h2>
                <div class="form-group">
                    <label>First Name:</label>
                    <input type="text" value="{{ user.name }}" readonly>
                </div>
                <div class="form-group">
                    <label>Last Name:</label>
                    <input type="text" value="{{ user.surname }}" readonly>
                </div>
                <div class="form-group">
                    <label>Username:</label>
                    <input type="text" value="{{ user.username }}" readonly>
                </div>
                <div class="form-actions">
                    <button type="submit" class="delete">Delete</button>
                    <a href="{% url 'licenses:license_list' %}" class="cancel">Cancel</a>
                </div>
            </form>
        </div>
    </content>
    </container>
{% endblock content %}

users/templates/users/users_edit.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Edit User
{% endblock title %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static '/css/users/users-edit.css' %}" />
{% endblock extra_css %}
{% block page_title %}
    Edit User
{% endblock page_title %}
{% block content %}
    <panel>
    <div class="inner-panel">
        <h3>User Tables:</h3>
        <ul>
            <li>
                <a href="{% url 'users:users_list' %}" class="selected">Users</a>
            </li>
            <li>
                <a href="{% url 'users:roles_list' %}">Roles</a>
            </li>
        </ul>
    </div>
    </panel>
    <container>
    <content-nav>
        <a href="{% url 'users:users_list' %}" class="action-tab">View Users</a>
        <a href="{% url 'users:users_add' %}" class="action-tab">Add User</a>
        <a class="action-tab selected">Edit User</a>
    </content-nav>
    <content>
        <div class="user-form-container">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label for="id_name">First Name:</label>
                    {{ form.name }}
                    {% if form.name.errors %}<div class="form-error">{{ form.name.errors }}</div>{% endif %}
                </div>
                <div class="form-group">
                    <label for="id_surname">Last Name:</label>
                    {{ form.surname }}
                    {% if form.surname.errors %}<div class="form-error">{{ form.surname.errors }}</div>{% endif %}
                </div>
                <div class="form-group">
                    <label for="id_position">Position:</label>
                    {{ form.position }}
                    {% if form.position.errors %}<div class="form-error">{{ form.position.errors }}</div>{% endif %}
                </div>
                <div class="form-group">
                    <label for="id_id_role">Role:</label>
                    {{ form.id_role }}
                    {% if form.id_role.errors %}<div class="form-error">{{ form.id_role.errors }}</div>{% endif %}
                </div>
                <div class="form-group">
                    <label for="id_email">E-mail:</label>
                    {{ form.email }}
                    {% if form.email.errors %}<div class="form-error">{{ form.email.errors }}</div>{% endif %}
                </div>
                <div class="form-group">
                    <label for="id_username">Username:</label>
                    {{ form.username }}
                    {% if form.username.errors %}<div class="form-error">{{ form.username.errors }}</div>{% endif %}
                </div>
                <div class="form-group">
                    <label for="id_password">Password:</label>
                    {{ form.password }}
                    {% if form.password.errors %}<div class="form-error">{{ form.password.errors }}</div>{% endif %}
                </div>
                <button type="submit">Save Changes</button>
            </form>
        </div>
    </content>
    </container>
{% endblock content %}

users/templates/users/users_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    Users List
{% endblock title %}
{% block extra_css %}
    <link rel="stylesheet" href="{% static '/css/users/users-list.css' %}" />
{% endblock extra_css %}
{% block page_title %}
    Users List
{% endblock page_title %}
{% block content %}
    <panel>
    <div class="inner-panel">
        <h3>Users Tables:</h3>
        <ul>
            <li>
                <a href="{% url 'users:users_list' %}" class="selected">Users</a>
            </li>
            <li>
                <a href="{% url 'users:roles_list' %}">Roles</a>
            </li>
        </ul>
    </div>
    </panel>
    <container>
    <content-nav>
        <a href="{% url 'users:users_list' %}" class="action-tab selected">View Users</a>
        <a href="{% url 'users:users_add' %}" class="action-tab">Add User</a>
    </content-nav>
    <content>
        <div class="user-list-header">
            <span class="user-id-header">ID</span>
            <span class="user-name-header">First Name</span>
            <span class="user-email-header">E-mail</span>
            <span class="user-role-header">Position</span>
            <span class="expand-icon-header"></span>
        </div>
        <div class="user-list">
            {% for user in users %}
                <div class="user-item">
                    <div class="user-summary">
                        <span class="user-id">{{ user.id }}</span>
                        <span class="user-name">{{ user.name }}</span>
                        <span class="user-email">{{ user.email }}</span>
                        <span class="user-role">{{ user.position }}</span>
                        <span class="expand-icon">▼</span>
                    </div>
                    <div class="user-details">
                        <p>
                            <strong>First Name:</strong> {{ user.name }}
                        </p>
                        <p>
                            <strong>Last Name:</strong> {{ user.surname }}
                        </p>
                        <p>
                            <strong>E-mail:</strong> {{ user.email }}
                        </p>
                        <p>
                            <strong>Position:</strong> {{ user.position }}
                        </p>
                        <p>
                            <strong>Role:</strong> {{ user.id_role.name }}
                        </p>
                        <h3>Actions</h3>
                        <a href="{% url 'users:users_edit' pk=user.pk %}" class="edit">Edit</a>
                        <a href="{% url 'users:users_delete' pk=user.pk %}" class="delete">Delete</a>
                    </div>
                </div>
            {% empty %}
                <div class="user-item">
                    <div class="user-summary">
                        <span class="empty-list-message empty-list-message-centered">No users to display.</span>
                    </div>
                </div>
            {% endfor %}
        </div>
    </content>
    </container>
{% endblock content %}
{% block extra_js %}
    <script>
    $(document).ready(function () {
      $('.user-summary').on('click', function (event) {
        if ($(event.target).closest('a').length && $(event.target).closest('.user-summary').length) {
          return;
        }
        $(this).siblings('.user-details').slideToggle();
        $(this).find('.expand-icon').toggleClass('expanded');
      });
    });
    </script>
{% endblock extra_js %}